export const nationalities = {
  us: "American",
  an: "Angolan",
  br: "Brazilian",
  uk: "British",
  gr: "Greek",
  it: "Italian",
  mx: "Mexican",
  ni: "Nigerian",
  pt: "Portuguese",
  es: "Spanish",
  tk: "Turkish",
  vn: "Vietnamese",
  other: "Other",
};
