import { User } from "@/interfaces/user";
import { randomUUID, UUID } from "crypto";

export const pseudoUsers: User[] = [
  {
    id: "1" as UUID,
    first_name: "John",
    last_name: "Doe",
    phone_number: "+1234567890",
    pt_phone_number: "+351123456789",
    email: "john.doe@example.com",
    profile_picture: "https://example.com/john.jpg",
    nationality: "American",
    preferred_language: "en",
    room_number: 101,
    house_number: 1,
    arrival_date: new Date("2023-01-01"),
    departure_estimate: new Date("2023-12-31"),
    role: "user",
  },
  {
    id: "2" as UUID,
    first_name: "Jane",
    last_name: "Smith",
    phone_number: "+0987654321",
    pt_phone_number: "+351987654321",
    email: "jane.smith@example.com",
    profile_picture: "https://example.com/jane.jpg",
    nationality: "British",
    preferred_language: "pt",
    room_number: 102,
    house_number: 1,
    arrival_date: new Date("2023-02-01"),
    departure_estimate: new Date("2023-11-30"),
    role: "user",
  },
  {
    id: "3" as UUID,
    first_name: "Carlos",
    last_name: "Silva",
    phone_number: "+351912345678",
    pt_phone_number: "+351912345678",
    email: "carlos.silva@example.com",
    profile_picture: "https://example.com/carlos.jpg",
    nationality: "Portuguese",
    preferred_language: "pt",
    room_number: 103,
    house_number: 2,
    arrival_date: new Date("2023-03-01"),
    departure_estimate: new Date("2023-10-31"),
    role: "user",
  },
  {
    id: "4" as UUID,
    first_name: "Alice",
    last_name: "Johnson",
    phone_number: "+1234567891",
    pt_phone_number: "+351123456781",
    email: "alice.johnson@example.com",
    profile_picture: "https://example.com/alice.jpg",
    nationality: "Canadian",
    preferred_language: "en",
    room_number: 104,
    house_number: 2,
    arrival_date: new Date("2023-04-01"),
    departure_estimate: new Date("2023-09-30"),
    role: "user",
  },
  {
    id: "5" as UUID,
    first_name: "Bob",
    last_name: "Brown",
    phone_number: "+1234567892",
    pt_phone_number: "+351123456782",
    email: "bob.brown@example.com",
    profile_picture: "https://example.com/bob.jpg",
    nationality: "Australian",
    preferred_language: "en",
    room_number: 105,
    house_number: 3,
    arrival_date: new Date("2023-05-01"),
    departure_estimate: new Date("2023-08-31"),
    role: "user",
  },
  {
    id: "6" as UUID,
    first_name: "Emma",
    last_name: "Garcia",
    phone_number: "+34678901234",
    pt_phone_number: "+351678901234",
    email: "emma.garcia@example.com",
    profile_picture: "https://example.com/emma.jpg",
    nationality: "Spanish",
    preferred_language: "es",
    room_number: 106,
    house_number: 3,
    arrival_date: new Date("2023-06-01"),
    departure_estimate: new Date("2023-12-15"),
    role: "user",
  },
  {
    id: "7" as UUID,
    first_name: "Liam",
    last_name: "Miller",
    phone_number: "+12125551234",
    pt_phone_number: "+3512125551234",
    email: "liam.miller@example.com",
    profile_picture: "https://example.com/liam.jpg",
    nationality: "Irish",
    preferred_language: "en",
    room_number: 107,
    house_number: 4,
    arrival_date: new Date("2023-07-01"),
    departure_estimate: new Date("2023-11-30"),
    role: "user",
  },
  {
    id: "8" as UUID,
    first_name: "Sophie",
    last_name: "Dubois",
    phone_number: "+33123456789",
    pt_phone_number: "+351312345678",
    email: "sophie.dubois@example.com",
    profile_picture: "https://example.com/sophie.jpg",
    nationality: "French",
    preferred_language: "fr",
    room_number: 108,
    house_number: 4,
    arrival_date: new Date("2023-08-01"),
    departure_estimate: new Date("2023-12-20"),
    role: "user",
  },
];
